server {
    listen 80;
    listen [::]:80;
    server_name taskspace.duckdns.org;

    include /etc/nginx/snippets/tasks-locations.conf;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name taskspace.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/taskspace.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/taskspace.duckdns.org/privkey.pem;

    include /etc/nginx/snippets/tasks-locations.conf;
}
